apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  namespace: ingress-basic
  name: whale-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - http:
        paths:
          - path: /blue-whale
            pathType: Prefix
            backend:
              service:
                name: blue-whale-service
                port:
                  number: 80
          - path: /purple-whale
            pathType: Prefix
            backend:
              service:
                name: purple-whale-service
                port:
                  number: 80