apiVersion: v1
kind: Service
metadata:
  namespace: ingress-basic
  name: blue-whale-service
spec:
  type: NodePort
  selector:
    app: blue-whale
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30000
---
apiVersion: v1
kind: Service
metadata:
  namespace: ingress-basic
  name: purple-whale-service
spec:
  type: NodePort
  selector:
    app: purple-whale
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30001
