apiVersion: v1
kind: Service
metadata:
  namespace: ingress-basic
  name: blue-whale-service
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  selector:
    app: blue-whale
---
apiVersion: v1
kind: Service
metadata:
  namespace: ingress-basic
  name: purple-whale-service
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  selector:
    app: purple-whale
